In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202101.csv', encoding='cp949')
df2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202102.csv', encoding='cp949')
df3 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202103.csv', encoding='cp949')
df4 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202104.csv', encoding='cp949')
df5 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202105.csv', encoding='cp949')
df6 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202106.csv', encoding='cp949')
df7 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202107.csv', encoding='cp949')
df8 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202108.csv', encoding='cp949')
df9 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202109.csv', encoding='cp949')
df10 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202110.csv', encoding='cp949')
df11 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202111.csv', encoding='cp949')
df12 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/BUS_STATION_BOARDING_MONTH_2021/BUS_STATION_BOARDING_MONTH_202112.csv', encoding='cp949')

In [ ]:
df12.head()

,사용일자,노선번호,노선명,버스정류장ARS번호,역명,승차총승객수,하차총승객수,등록일자
0,20211201,100,100번(하계동~용산구청),11428,한성여객종점,14,0,20211204
1,20211201,100,100번(하계동~용산구청),11374,서울시립북서울미술관,60,1,20211204
2,20211201,100,100번(하계동~용산구청),11380,목련아파트상가,264,60,20211204
3,20211201,100,100번(하계동~용산구청),11339,월계보건지소,184,131,20211204
4,20211201,100,100번(하계동~용산구청),01002,창경궁.서울대학교병원,99,163,20211204

In [ ]:
# df5['사용일자'] = df5.index
# df6['사용일자'] = df6.index
# df5 = df5.reset_index(drop=True)
# df6 = df6.reset_index(drop=True)
# df7 = df7.drop('bus_route_id', axis=1)
# df7.columns = df1.columns

In [ ]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12], axis=0)

del df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12

In [ ]:
df.shape

(14032133, 8)

In [ ]:
df['사용일자']

0          20210101
1          20210101
2          20210101
3          20210101
4          20210101
             ...
1200517    20211231
1200518    20211231
1200519    20211231
1200520    20211231
1200521    20211231
Name: 사용일자, Length: 14032133, dtype: int64

In [ ]:
df['사용일자'].min(), df['사용일자'].max()

(20210101, 20211231)

In [ ]:
def extract_gu(x):
    try:
        gu = str(x).split(' ')[1]
        return gu
    except:
        gu = 'nan'
        return gu

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/21년.csv')
df2

,표준ID,ARS-ID,정류소명,X좌표,Y좌표,_PARCEL_AD,_ROAD_AD
0,100000001,1001,종로2가사거리,126.987786,37.569764,서울특별시 종로구 종로2가 84-11,서울특별시 종로구 종로2가 삼일대로 396
1,100000002,1002,창경궁.서울대학교병원,126.996520,37.579179,서울특별시 종로구 와룡동 2-87,서울특별시 종로구 창경궁로 202-1
2,100000003,1003,명륜3가.성대입구,126.998290,37.582709,서울특별시 종로구 명륜4가 193-2,서울특별시 종로구 명륜4가 창경궁로 233
3,100000004,1004,종로2가.삼일교,126.987507,37.568582,서울특별시 종로구 관철동 268,서울특별시 종로구 삼일대로15길 1
4,100000005,1005,혜화동로터리.여운형활동터,127.001694,37.586230,서울특별시 종로구 혜화동 56,서울특별시 종로구 창경궁로 283
...,...,...,...,...,...,...,...
10916,124000334,25995,우성아파트,127.139326,37.550442,서울특별시 강동구 천호동 19-1,서울특별시 강동구 구천면로 368
10917,124000333,25996,우성아파트,127.140052,37.550620,서울특별시 강동구 암사동 421-110,서울특별시 강동구 구천면로 373
10918,124000332,25997,조일약국,127.123477,37.533686,서울특별시 강동구 성내동 118-2,서울특별시 강동구 천호옛길 50
10919,124000331,25998,성내시장,127.125410,37.536199,서울특별시 강동구 성내동 38-2,서울특별시 강동구 천호옛길 83
10920,124000330,25999,천호우체국.로데오거리,127.127354,37.540390,서울특별시 강동구 천호동 407-5,서울특별시 강동구 천호대로157길 53-7

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/21년.csv')

df2['ARS-ID'] = df2['ARS-ID'].apply(lambda x : '0'+str(x) if len(str(x))==4 else str(x))
df2['구'] = df2['_PARCEL_AD'].apply(lambda x : extract_gu(x))

lst = ['광진구', '동대문구', '성동구', '중랑구']
df2 = df2.query("구 in @lst").reset_index(drop=True)

df2.head()

,표준ID,ARS-ID,정류소명,X좌표,Y좌표,_PARCEL_AD,_ROAD_AD,구
0,101900001,02518,응봉근린공원.금호산,127.017028,37.553782,서울특별시 성동구 금호동2가 산 9-1,서울특별시 성동구 금호동2가 금호산15길 17-1,성동구
1,103000001,04001,답십리역사거리,127.054369,37.565426,서울특별시 성동구 용답동 127,서울특별시 성동구 천호대로 308,성동구
2,103000002,04002,청년회의소.서울새활용플라자,127.060479,37.561952,서울특별시 성동구 용답동 224-2,서울특별시 성동구 천호대로 376,성동구
3,103000003,04003,장한평역,127.066098,37.561131,서울특별시 성동구 용답동 224-3,서울특별시 성동구 천호대로 426-1,성동구
4,103000004,04101,상왕십리역,127.029260,37.564279,서울특별시 성동구 하왕십리동 903-1,서울특별시 성동구 왕십리로 367,성동구

In [ ]:
df2.shape

(1419, 8)

In [ ]:
df3 = df.merge(df2[['ARS-ID', '구']], left_on='버스정류장ARS번호', right_on='ARS-ID')

In [ ]:
df3

,사용일자,노선번호,노선명,버스정류장ARS번호,역명,승차총승객수,하차총승객수,등록일자,ARS-ID,구
0,20210101,2211,2211번(면목동~회기역),06154,하나은행장안동지점,32,50,20210104,06154,동대문구
1,20210101,2211,2211번(면목동~회기역),06154,하나은행장안동지점,22,42,20210104,06154,동대문구
2,20210101,145,145번(번동~강남역),06154,하나은행장안동지점,35,44,20210104,06154,동대문구
3,20210101,3220,3220번(오금동~청량리),06154,하나은행장안동지점,5,36,20210104,06154,동대문구
4,20210102,2211,2211번(면목동~회기역),06154,하나은행장안동지점,30,70,20210105,06154,동대문구
...,...,...,...,...,...,...,...,...,...,...
1609503,20211227,광진01,광진01(광진정보도서관~워커힐아파트),05265,광진청소년수련관,113,52,20211230,05265,광진구
1609504,20211228,광진01,광진01(광진정보도서관~워커힐아파트),05265,광진청소년수련관,108,49,20211231,05265,광진구
1609505,20211229,광진01,광진01(광진정보도서관~워커힐아파트),05265,광진청소년수련관,123,66,20220101,05265,광진구
1609506,20211230,광진01,광진01(광진정보도서관~워커힐아파트),05265,광진청소년수련관,122,59,20220102,05265,광진구
1609507,20211231,광진01,광진01(광진정보도서관~워커힐아파트),05265,광진청소년수련관,101,43,20220103,05265,광진구

In [ ]:
df3['구'].unique()

array(['동대문구', '중랑구', '광진구', '성동구'], dtype=object)

In [ ]:
df4 = df3.groupby(['사용일자', '구'])['하차총승객수'].mean().reset_index()
df5 = df3.groupby(['사용일자', '구'])['하차총승객수'].sum().reset_index()
df6 = df3.groupby(['사용일자', '구'])['하차총승객수'].size().reset_index()
df7 = df4.merge(df5, on=['사용일자', '구'])
df7 = df7.merge(df6, on=['사용일자', '구'])
df7.columns = ['사용일자', '구', '하차총승객수_mean', '하차총승객수_sum', '하차총승객수_size']
df7

          사용일자     구  하차총승객수_mean  하차총승객수_sum  하차총승객수_size
0     20210101   광진구    42.800824       31159          728
1     20210101  동대문구    40.710750       52639         1293
2     20210101   성동구    28.300931       27367          967
3     20210101   중랑구    28.546942       40137         1406
4     20210102   광진구    63.590096       46230          727
...        ...   ...          ...         ...          ...
1455  20211230   중랑구    90.006267      129249         1436
1456  20211231   광진구   120.239272       92464          769
1457  20211231  동대문구   130.638739      169961         1301
1458  20211231   성동구    94.612016       92909          982
1459  20211231   중랑구    88.519191      126848         1433

[1460 rows x 5 columns]

In [ ]:
df3.groupby(['구'])['ARS-ID'].nunique()

구
광진구     271
동대문구    309
성동구     444
중랑구     380
Name: ARS-ID, dtype: int64

In [ ]:
df7.to_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/hacha_2021.csv', index=False)

In [ ]:
df18 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/hacha_2018.csv')
df19 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/hacha_2019.csv')
df20 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/hacha_2020.csv')
df21 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/hacha_2021.csv')

In [ ]:
data = pd.concat([df18, df19, df20, df21], axis=0).reset_index(drop=True)

In [ ]:
data.to_csv('/content/drive/MyDrive/Colab Notebooks/dacon/ddareung/ex_data/hacha_1821.csv')